import Head from 'next/head'
import Crds from '../comp/crd'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Cards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Crds/>
      </div>
    </div>
  )
}
